name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  NODE_FLAGS: --max_old_space_size=4096

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      - name: Set up project
        uses: ./.github/actions/setup-project
      - name: Build
        run: |
          rm -rf dist
          pnpm run build
        env:
          SCOREBOARD_SERVER: ${{ secrets.SCOREBOARD_SERVER }}
      - name: Compress build output
        if: always()
        run: tar -cvzf dist.tar.gz bemuse/dist
      - name: Checks
        run: pnpm run --filter bemuse pre-deploy
      - name: Release
        if: github.event_name == 'push'
        id: release
        run: |
          pnpm run release --confirm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: bemuse-build-${{ github.sha }}
          path: dist.tar.gz
    outputs:
      released-tag: ${{ steps.release.outputs.tag }}
  e2e:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
      - name: Set up project
        uses: ./.github/actions/setup-project
      - name: Download build
        uses: actions/download-artifact@v7
        with:
          name: bemuse-build-${{ github.sha }}
          path: '.'
      - name: Extract build
        run: tar -xvzf dist.tar.gz
      - name: Install browsers
        run: |
          cd e2e
          npx playwright install --with-deps
      - name: Run E2E tests
        run: |
          cd e2e
          npx playwright test
      - name: Upload test report
        uses: actions/upload-artifact@v6
        if: always()
        with:
          name: playwright-report
          path: e2e/playwright-report
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up project
        uses: ./.github/actions/setup-project
      - name: Build dependencies
        run: pnpm run build
      - name: Typecheck
        run: pnpm run --filter bemuse typecheck
  tidy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up project
        uses: ./.github/actions/setup-project
      - name: Build
        run: pnpm run build
      - name: Lint all
        run: pnpm run lint
        if: always()
      - name: Semgrep
        uses: ./.github/actions/semgrep
        if: always()
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up project
        uses: ./.github/actions/setup-project
      - name: Build
        run: pnpm run --filter bemuse build
      - name: Test
        run: pnpm run --filter bemuse test
        working-directory: bemuse
      - uses: codecov/codecov-action@v5
        with:
          use_oidc: true
  test_packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up project
        uses: ./.github/actions/setup-project
      - name: Build
        run: pnpm run build
      - name: Test Packages
        run: pnpm run test-packages
      - uses: codecov/codecov-action@v5
        with:
          use_oidc: true
